from sklearn.feature_extraction.text import CountVectorizer

TAGALOG_STOPWORDS = [
    "ang",
    "ng",
    "na",
    "sa",
    "at",
    "ay",
    "mga",
    "po",
    "ito",
    "ko",
    "mo",
    "siya",
    "kami",
    "kayo",
    "sila",
    "ako",
    "ikaw",
    "nung",
    "yung",
    "nya",
    "niya",
    "namin",
    "natin",
    "para",
    "pero",
    "kung",
    "kasi",
    "lang",
    "din",
    "rin",
    "dito",
    "diyan",
    "doon",
    "hindi",
    "nang",
    "dahil",
    "kung",
    "kapag",
    "noon",
    "ngayon",
    "pag",
    "talaga",
    "nga",
    "naman",
    "yun",
    "yan",
    "yon",
    "daw",
    "raw",
    "mag",
    "minsan",
    "naiintindihan",
    "hindi",
    "dapat",
    "gusto",
    "pwede",
    "lagi",
    "lahat",
    "meron",
    "wala",
]


def get_combined_stopwords() -> list[str]:
    english_stopwords = list(CountVectorizer(stop_words="english").get_stop_words())
    return english_stopwords + TAGALOG_STOPWORDS
